# Generated by Django 5.2.1 on 2025-05-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('usado', 'Usado'), ('penalizado', 'Penalizado'), ('expirado', 'Expirado')], default='pendiente', max_length=20)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('reclamado_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
