# Generated by Django 5.2.1 on 2025-05-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='codigo_turno',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
