# Generated by Django 5.2.1 on 2025-05-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_turno_codigo_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('usado', 'Usado'), ('entregado', 'Entregado'), ('penalizado', 'Penalizado'), ('expirado', 'Expirado')], default='pendiente', max_length=20),
        ),
    ]
