# Generated by Django 5.2.1 on 2025-05-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalizacion',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-27 18:30:00'),
            preserve_default=False,
        ),
    ]
