# Generated by Django 5.2.1 on 2025-05-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteria',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('reabasteciendo', 'Reabasteciendo')], default='cerrada', max_length=20),
        ),
    ]
